import {assets, credentialDefinitions} from '../../database/schema';
import {
    CredentialAttribute,
    CredentialRepresentation,
    RevocationInfo
} from '../rest';

// $inferSelect does not respect nullability of fields and the type has every field as required
export type Asset = typeof assets.$inferSelect;
// $inferInsert only provides fields that are notNull() or generated by default. This seems to be a bug in DrizzleORM or very not pleasant choice
export type NewAsset = typeof assets.$inferInsert & { fileName?: string, description?: string };

// $inferSelect does not respect nullability of fields and the type has every field as required
export type CredentialDefinition = typeof credentialDefinitions.$inferSelect & {
    attributes: CredentialAttribute[]
    representations: CredentialRepresentation[]
    revocation?: RevocationInfo
};
// $inferInsert only provides fields that are notNull() or generated by default. This seems to be a bug in DrizzleORM or very not pleasant choice
export type NewCredentialDefinition = typeof credentialDefinitions.$inferInsert & {
    attributes: CredentialAttribute[]
    representations: CredentialRepresentation[]
    revocation?: RevocationInfo
};
