import { assets } from '../../database/schema';
import { personas } from '../../database/schema'

// $inferSelect does not respect nullability of fields and the type has every field as required
export type Asset = typeof assets.$inferSelect;
// $inferInsert only provides fields that are notNull() or generated by default. This seems to be a bug in DrizzleORM or very not pleasant choice
export type NewAsset = typeof assets.$inferInsert & { fileName?: string | null, description?: string | null };

// $inferSelect does not respect nullability of fields and the type has every field as required
export type Persona = typeof personas.$inferSelect;
// $inferInsert only provides fields that are notNull() or generated by default. This seems to be a bug in DrizzleORM or very not pleasant choice
export type NewPersona = typeof personas.$inferInsert & { description?: string, headshotImageId?: string, bodyImageId?: string };
