/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Anonymous Credentials specific revocation information
 * @export
 * @interface AnonCredRevocation
 */
export interface AnonCredRevocation {
    /**
     * Title of the revocation information
     * @type {string}
     * @memberof AnonCredRevocation
     */
    title: string;
    /**
     * Detailed description of the revocation process or requirements
     * @type {string}
     * @memberof AnonCredRevocation
     */
    description?: string;
    /**
     * Identifier of the revocation registry for AnonCreds
     * @type {string}
     * @memberof AnonCredRevocation
     */
    registryId: string;
}

/**
 * Check if a given object implements the AnonCredRevocation interface.
 */
export function instanceOfAnonCredRevocation(value: object): value is AnonCredRevocation {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('registryId' in value) || value['registryId'] === undefined) return false;
    return true;
}

export function AnonCredRevocationFromJSON(json: any): AnonCredRevocation {
    return AnonCredRevocationFromJSONTyped(json, false);
}

export function AnonCredRevocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnonCredRevocation {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'registryId': json['registryId'],
    };
}

export function AnonCredRevocationToJSON(json: any): AnonCredRevocation {
    return AnonCredRevocationToJSONTyped(json, false);
}

export function AnonCredRevocationToJSONTyped(value?: AnonCredRevocation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'registryId': value['registryId'],
    };
}

