/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AriesRequestCredentialAttributes } from './AriesRequestCredentialAttributes';
import {
    AriesRequestCredentialAttributesFromJSON,
    AriesRequestCredentialAttributesFromJSONTyped,
    AriesRequestCredentialAttributesToJSON,
    AriesRequestCredentialAttributesToJSONTyped,
} from './AriesRequestCredentialAttributes';
import type { AriesRequestCredentialPredicates } from './AriesRequestCredentialPredicates';
import {
    AriesRequestCredentialPredicatesFromJSON,
    AriesRequestCredentialPredicatesFromJSONTyped,
    AriesRequestCredentialPredicatesToJSON,
    AriesRequestCredentialPredicatesToJSONTyped,
} from './AriesRequestCredentialPredicates';

/**
 * 
 * @export
 * @interface AriesProofRequest
 */
export interface AriesProofRequest {
    /**
     * Map of attribute groups requested in the proof
     * @type {{ [key: string]: AriesRequestCredentialAttributes; }}
     * @memberof AriesProofRequest
     */
    attributes?: { [key: string]: AriesRequestCredentialAttributes; };
    /**
     * Map of predicate groups requested in the proof
     * @type {{ [key: string]: AriesRequestCredentialPredicates; }}
     * @memberof AriesProofRequest
     */
    predicates?: { [key: string]: AriesRequestCredentialPredicates; };
}

/**
 * Check if a given object implements the AriesProofRequest interface.
 */
export function instanceOfAriesProofRequest(value: object): value is AriesProofRequest {
    return true;
}

export function AriesProofRequestFromJSON(json: any): AriesProofRequest {
    return AriesProofRequestFromJSONTyped(json, false);
}

export function AriesProofRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AriesProofRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'attributes': json['attributes'] == null ? undefined : (mapValues(json['attributes'], AriesRequestCredentialAttributesFromJSON)),
        'predicates': json['predicates'] == null ? undefined : (mapValues(json['predicates'], AriesRequestCredentialPredicatesFromJSON)),
    };
}

export function AriesProofRequestToJSON(json: any): AriesProofRequest {
    return AriesProofRequestToJSONTyped(json, false);
}

export function AriesProofRequestToJSONTyped(value?: AriesProofRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attributes': value['attributes'] == null ? undefined : (mapValues(value['attributes'], AriesRequestCredentialAttributesToJSON)),
        'predicates': value['predicates'] == null ? undefined : (mapValues(value['predicates'], AriesRequestCredentialPredicatesToJSON)),
    };
}

