/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Asset
 */
export interface Asset {
    /**
     * Unique identifier for the asset
     * @type {string}
     * @memberof Asset
     */
    id?: string;
    /**
     * External reference identifier for the asset
     * @type {string}
     * @memberof Asset
     */
    assetId: string;
    /**
     * Type of asset (e.g., image, document, icon)
     * @type {string}
     * @memberof Asset
     */
    assetType: string;
    /**
     * URL or file path to access the asset content
     * @type {string}
     * @memberof Asset
     */
    urlOrPath: string;
}

/**
 * Check if a given object implements the Asset interface.
 */
export function instanceOfAsset(value: object): value is Asset {
    if (!('assetId' in value) || value['assetId'] === undefined) return false;
    if (!('assetType' in value) || value['assetType'] === undefined) return false;
    if (!('urlOrPath' in value) || value['urlOrPath'] === undefined) return false;
    return true;
}

export function AssetFromJSON(json: any): Asset {
    return AssetFromJSONTyped(json, false);
}

export function AssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Asset {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'assetId': json['assetId'],
        'assetType': json['assetType'],
        'urlOrPath': json['urlOrPath'],
    };
}

export function AssetToJSON(json: any): Asset {
    return AssetToJSONTyped(json, false);
}

export function AssetToJSONTyped(value?: Asset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'assetId': value['assetId'],
        'assetType': value['assetType'],
        'urlOrPath': value['urlOrPath'],
    };
}

