/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CredentialAttribute } from './CredentialAttribute';
import {
    CredentialAttributeFromJSON,
    CredentialAttributeFromJSONTyped,
    CredentialAttributeToJSON,
    CredentialAttributeToJSONTyped,
} from './CredentialAttribute';
import type { CredentialDefinitionRevocation } from './CredentialDefinitionRevocation';
import {
    CredentialDefinitionRevocationFromJSON,
    CredentialDefinitionRevocationFromJSONTyped,
    CredentialDefinitionRevocationToJSON,
    CredentialDefinitionRevocationToJSONTyped,
} from './CredentialDefinitionRevocation';
import type { ListCredentialRepresentations200ResponseInner } from './ListCredentialRepresentations200ResponseInner';
import {
    ListCredentialRepresentations200ResponseInnerFromJSON,
    ListCredentialRepresentations200ResponseInnerFromJSONTyped,
    ListCredentialRepresentations200ResponseInnerToJSON,
    ListCredentialRepresentations200ResponseInnerToJSONTyped,
} from './ListCredentialRepresentations200ResponseInner';
import type { Asset } from './Asset';
import {
    AssetFromJSON,
    AssetFromJSONTyped,
    AssetToJSON,
    AssetToJSONTyped,
} from './Asset';
import type { CredentialType } from './CredentialType';
import {
    CredentialTypeFromJSON,
    CredentialTypeFromJSONTyped,
    CredentialTypeToJSON,
    CredentialTypeToJSONTyped,
} from './CredentialType';

/**
 * 
 * @export
 * @interface CredentialDefinition
 */
export interface CredentialDefinition {
    /**
     * Unique identifier for the credential definition
     * @type {string}
     * @memberof CredentialDefinition
     */
    id?: string;
    /**
     * Name of the credential definition
     * @type {string}
     * @memberof CredentialDefinition
     */
    name: string;
    /**
     * Version of the credential definition
     * @type {string}
     * @memberof CredentialDefinition
     */
    version: string;
    /**
     * 
     * @type {CredentialType}
     * @memberof CredentialDefinition
     */
    type: CredentialType;
    /**
     * List of attributes in the credential definition
     * @type {Array<CredentialAttribute>}
     * @memberof CredentialDefinition
     */
    attributes?: Array<CredentialAttribute>;
    /**
     * List of representations for this credential definition
     * @type {Array<ListCredentialRepresentations200ResponseInner>}
     * @memberof CredentialDefinition
     */
    representations?: Array<ListCredentialRepresentations200ResponseInner>;
    /**
     * 
     * @type {CredentialDefinitionRevocation}
     * @memberof CredentialDefinition
     */
    revocation?: CredentialDefinitionRevocation;
    /**
     * 
     * @type {Asset}
     * @memberof CredentialDefinition
     */
    icon?: Asset;
}



/**
 * Check if a given object implements the CredentialDefinition interface.
 */
export function instanceOfCredentialDefinition(value: object): value is CredentialDefinition {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CredentialDefinitionFromJSON(json: any): CredentialDefinition {
    return CredentialDefinitionFromJSONTyped(json, false);
}

export function CredentialDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'version': json['version'],
        'type': CredentialTypeFromJSON(json['type']),
        'attributes': json['attributes'] == null ? undefined : ((json['attributes'] as Array<any>).map(CredentialAttributeFromJSON)),
        'representations': json['representations'] == null ? undefined : ((json['representations'] as Array<any>).map(ListCredentialRepresentations200ResponseInnerFromJSON)),
        'revocation': json['revocation'] == null ? undefined : CredentialDefinitionRevocationFromJSON(json['revocation']),
        'icon': json['icon'] == null ? undefined : AssetFromJSON(json['icon']),
    };
}

export function CredentialDefinitionToJSON(json: any): CredentialDefinition {
    return CredentialDefinitionToJSONTyped(json, false);
}

export function CredentialDefinitionToJSONTyped(value?: CredentialDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'version': value['version'],
        'type': CredentialTypeToJSON(value['type']),
        'attributes': value['attributes'] == null ? undefined : ((value['attributes'] as Array<any>).map(CredentialAttributeToJSON)),
        'representations': value['representations'] == null ? undefined : ((value['representations'] as Array<any>).map(ListCredentialRepresentations200ResponseInnerToJSON)),
        'revocation': CredentialDefinitionRevocationToJSON(value['revocation']),
        'icon': AssetToJSON(value['icon']),
    };
}

