/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CredentialAttributeType } from './CredentialAttributeType';
import {
    CredentialAttributeTypeFromJSON,
    CredentialAttributeTypeFromJSONTyped,
    CredentialAttributeTypeToJSON,
    CredentialAttributeTypeToJSONTyped,
} from './CredentialAttributeType';

/**
 * 
 * @export
 * @interface CredentialAttribute
 */
export interface CredentialAttribute {
    /**
     * Name of the attribute
     * @type {string}
     * @memberof CredentialAttribute
     */
    name: string;
    /**
     * Default or example value of the attribute
     * @type {string}
     * @memberof CredentialAttribute
     */
    value?: string;
    /**
     * 
     * @type {CredentialAttributeType}
     * @memberof CredentialAttribute
     */
    type: CredentialAttributeType;
}



/**
 * Check if a given object implements the CredentialAttribute interface.
 */
export function instanceOfCredentialAttribute(value: object): value is CredentialAttribute {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CredentialAttributeFromJSON(json: any): CredentialAttribute {
    return CredentialAttributeFromJSONTyped(json, false);
}

export function CredentialAttributeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialAttribute {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'] == null ? undefined : json['value'],
        'type': CredentialAttributeTypeFromJSON(json['type']),
    };
}

export function CredentialAttributeToJSON(json: any): CredentialAttribute {
    return CredentialAttributeToJSONTyped(json, false);
}

export function CredentialAttributeToJSONTyped(value?: CredentialAttribute | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': value['value'],
        'type': CredentialAttributeTypeToJSON(value['type']),
    };
}

