/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Persona } from './Persona';
import {
    PersonaFromJSON,
    PersonaFromJSONTyped,
    PersonaToJSON,
    PersonaToJSONTyped,
} from './Persona';
import type { Issuer } from './Issuer';
import {
    IssuerFromJSON,
    IssuerFromJSONTyped,
    IssuerToJSON,
    IssuerToJSONTyped,
} from './Issuer';
import type { Step } from './Step';
import {
    StepFromJSON,
    StepFromJSONTyped,
    StepToJSON,
    StepToJSONTyped,
} from './Step';

/**
 * Workflow specialization for credential issuance
 * @export
 * @interface IssuanceFlow
 */
export interface IssuanceFlow {
    /**
     * Unique identifier for the workflow
     * @type {string}
     * @memberof IssuanceFlow
     */
    id?: string;
    /**
     * Name of the workflow
     * @type {string}
     * @memberof IssuanceFlow
     */
    name: string;
    /**
     * Detailed description of the workflow
     * @type {string}
     * @memberof IssuanceFlow
     */
    description?: string;
    /**
     * Ordered list of steps in the workflow
     * @type {Array<Step>}
     * @memberof IssuanceFlow
     */
    steps?: Array<Step>;
    /**
     * List of personas involved in the workflow
     * @type {Array<Persona>}
     * @memberof IssuanceFlow
     */
    personas?: Array<Persona>;
    /**
     * Identifier of the issuer for this flow
     * @type {string}
     * @memberof IssuanceFlow
     */
    issuerId: string;
    /**
     * 
     * @type {Issuer}
     * @memberof IssuanceFlow
     */
    issuer?: Issuer;
}

/**
 * Check if a given object implements the IssuanceFlow interface.
 */
export function instanceOfIssuanceFlow(value: object): value is IssuanceFlow {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('issuerId' in value) || value['issuerId'] === undefined) return false;
    return true;
}

export function IssuanceFlowFromJSON(json: any): IssuanceFlow {
    return IssuanceFlowFromJSONTyped(json, false);
}

export function IssuanceFlowFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuanceFlow {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'steps': json['steps'] == null ? undefined : ((json['steps'] as Array<any>).map(StepFromJSON)),
        'personas': json['personas'] == null ? undefined : ((json['personas'] as Array<any>).map(PersonaFromJSON)),
        'issuerId': json['issuerId'],
        'issuer': json['issuer'] == null ? undefined : IssuerFromJSON(json['issuer']),
    };
}

export function IssuanceFlowToJSON(json: any): IssuanceFlow {
    return IssuanceFlowToJSONTyped(json, false);
}

export function IssuanceFlowToJSONTyped(value?: IssuanceFlow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'steps': value['steps'] == null ? undefined : ((value['steps'] as Array<any>).map(StepToJSON)),
        'personas': value['personas'] == null ? undefined : ((value['personas'] as Array<any>).map(PersonaToJSON)),
        'issuerId': value['issuerId'],
        'issuer': IssuerToJSON(value['issuer']),
    };
}

