/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CredentialRepresentation } from './CredentialRepresentation';
import {
    instanceOfCredentialRepresentation,
    CredentialRepresentationFromJSON,
    CredentialRepresentationFromJSONTyped,
    CredentialRepresentationToJSON,
} from './CredentialRepresentation';
import type { OCARepresentation } from './OCARepresentation';
import {
    instanceOfOCARepresentation,
    OCARepresentationFromJSON,
    OCARepresentationFromJSONTyped,
    OCARepresentationToJSON,
} from './OCARepresentation';

/**
 * @type ListCredentialRepresentations200ResponseInner
 * 
 * @export
 */
export type ListCredentialRepresentations200ResponseInner = CredentialRepresentation | OCARepresentation;

export function ListCredentialRepresentations200ResponseInnerFromJSON(json: any): ListCredentialRepresentations200ResponseInner {
    return ListCredentialRepresentations200ResponseInnerFromJSONTyped(json, false);
}

export function ListCredentialRepresentations200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCredentialRepresentations200ResponseInner {
    if (json == null) {
        return json;
    }
    if (instanceOfCredentialRepresentation(json)) {
        return CredentialRepresentationFromJSONTyped(json, true);
    }
    if (instanceOfOCARepresentation(json)) {
        return OCARepresentationFromJSONTyped(json, true);
    }

    return {} as any;
}

export function ListCredentialRepresentations200ResponseInnerToJSON(json: any): any {
    return ListCredentialRepresentations200ResponseInnerToJSONTyped(json, false);
}

export function ListCredentialRepresentations200ResponseInnerToJSONTyped(value?: ListCredentialRepresentations200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfCredentialRepresentation(value)) {
        return CredentialRepresentationToJSON(value as CredentialRepresentation);
    }
    if (instanceOfOCARepresentation(value)) {
        return OCARepresentationToJSON(value as OCARepresentation);
    }

    return {};
}

