/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AriesOOBAction } from './AriesOOBAction';
import {
    instanceOfAriesOOBAction,
    AriesOOBActionFromJSON,
    AriesOOBActionFromJSONTyped,
    AriesOOBActionToJSON,
} from './AriesOOBAction';
import type { StepAction } from './StepAction';
import {
    instanceOfStepAction,
    StepActionFromJSON,
    StepActionFromJSONTyped,
    StepActionToJSON,
} from './StepAction';

/**
 * @type ListStepActions200ResponseInner
 * 
 * @export
 */
export type ListStepActions200ResponseInner = AriesOOBAction | StepAction;

export function ListStepActions200ResponseInnerFromJSON(json: any): ListStepActions200ResponseInner {
    return ListStepActions200ResponseInnerFromJSONTyped(json, false);
}

export function ListStepActions200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListStepActions200ResponseInner {
    if (json == null) {
        return json;
    }
    if (instanceOfAriesOOBAction(json)) {
        return AriesOOBActionFromJSONTyped(json, true);
    }
    if (instanceOfStepAction(json)) {
        return StepActionFromJSONTyped(json, true);
    }

    return {} as any;
}

export function ListStepActions200ResponseInnerToJSON(json: any): any {
    return ListStepActions200ResponseInnerToJSONTyped(json, false);
}

export function ListStepActions200ResponseInnerToJSONTyped(value?: ListStepActions200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfAriesOOBAction(value)) {
        return AriesOOBActionToJSON(value as AriesOOBAction);
    }
    if (instanceOfStepAction(value)) {
        return StepActionToJSON(value as StepAction);
    }

    return {};
}

