/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RevocationInfo
 */
export interface RevocationInfo {
    /**
     * Title of the revocation information
     * @type {string}
     * @memberof RevocationInfo
     */
    title: string;
    /**
     * Detailed description of the revocation process or requirements
     * @type {string}
     * @memberof RevocationInfo
     */
    description?: string;
}

/**
 * Check if a given object implements the RevocationInfo interface.
 */
export function instanceOfRevocationInfo(value: object): value is RevocationInfo {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function RevocationInfoFromJSON(json: any): RevocationInfo {
    return RevocationInfoFromJSONTyped(json, false);
}

export function RevocationInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevocationInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function RevocationInfoToJSON(json: any): RevocationInfo {
    return RevocationInfoToJSONTyped(json, false);
}

export function RevocationInfoToJSONTyped(value?: RevocationInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
    };
}

