/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import { AriesOOBAction, AriesOOBActionFromJSONTyped, AriesOOBActionToJSON, AriesOOBActionToJSONTyped } from './AriesOOBAction';
/**
 * 
 * @export
 * @interface StepAction
 */
export interface StepAction {
    /**
     * Unique identifier for the action
     * @type {string}
     * @memberof StepAction
     */
    id?: string;
    /**
     * Type of action (e.g., CONNECT_WALLET, ARIES_OOB)
     * @type {string}
     * @memberof StepAction
     */
    type: string;
    /**
     * Title of the action
     * @type {string}
     * @memberof StepAction
     */
    title?: string;
    /**
     * Descriptive text for the action
     * @type {string}
     * @memberof StepAction
     */
    text?: string;
}

/**
 * Check if a given object implements the StepAction interface.
 */
export function instanceOfStepAction(value: object): value is StepAction {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function StepActionFromJSON(json: any): StepAction {
    return StepActionFromJSONTyped(json, false);
}

export function StepActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepAction {
    if (json == null) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['type'] === 'ARIES_OOB') {
            return AriesOOBActionFromJSONTyped(json, ignoreDiscriminator);
        }
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'],
        'title': json['title'] == null ? undefined : json['title'],
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function StepActionToJSON(json: any): StepAction {
    return StepActionToJSONTyped(json, false);
}

export function StepActionToJSONTyped(value?: StepAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (!ignoreDiscriminator) {
        switch (value['type']) {
            case 'ARIES_OOB':
                return AriesOOBActionToJSONTyped(value as AriesOOBAction, ignoreDiscriminator);
            default:
                throw new Error(`No variant of StepAction exists with 'type=${value['type']}'`);
        }
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'title': value['title'],
        'text': value['text'],
    };
}

