/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Persona } from './Persona';
import {
    PersonaFromJSON,
    PersonaFromJSONTyped,
    PersonaToJSON,
    PersonaToJSONTyped,
} from './Persona';
import type { Step } from './Step';
import {
    StepFromJSON,
    StepFromJSONTyped,
    StepToJSON,
    StepToJSONTyped,
} from './Step';

/**
 * Base class for all workflows
 * @export
 * @interface Workflow
 */
export interface Workflow {
    /**
     * Unique identifier for the workflow
     * @type {string}
     * @memberof Workflow
     */
    id?: string;
    /**
     * Name of the workflow
     * @type {string}
     * @memberof Workflow
     */
    name: string;
    /**
     * Detailed description of the workflow
     * @type {string}
     * @memberof Workflow
     */
    description?: string;
    /**
     * Ordered list of steps in the workflow
     * @type {Array<Step>}
     * @memberof Workflow
     */
    steps?: Array<Step>;
    /**
     * List of personas involved in the workflow
     * @type {Array<Persona>}
     * @memberof Workflow
     */
    personas?: Array<Persona>;
}

/**
 * Check if a given object implements the Workflow interface.
 */
export function instanceOfWorkflow(value: object): value is Workflow {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function WorkflowFromJSON(json: any): Workflow {
    return WorkflowFromJSONTyped(json, false);
}

export function WorkflowFromJSONTyped(json: any, ignoreDiscriminator: boolean): Workflow {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'steps': json['steps'] == null ? undefined : ((json['steps'] as Array<any>).map(StepFromJSON)),
        'personas': json['personas'] == null ? undefined : ((json['personas'] as Array<any>).map(PersonaFromJSON)),
    };
}

export function WorkflowToJSON(json: any): Workflow {
    return WorkflowToJSONTyped(json, false);
}

export function WorkflowToJSONTyped(value?: Workflow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'steps': value['steps'] == null ? undefined : ((value['steps'] as Array<any>).map(StepToJSON)),
        'personas': value['personas'] == null ? undefined : ((value['personas'] as Array<any>).map(PersonaToJSON)),
    };
}

